version: "3"

services:
### postgres DB  service ###
### https://hub.docker.com/_/postgres ###
  booking-db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5434:5432"

### booking service ###
  booking:
    image: test:test
    depends_on:
      - booking-db