spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/booking
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: classpath*:database/initDB.sql
    data: classpath*:database/populateDB.sql

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true